;
; File generated by cc65 v 2.19 - Git 4f87c7c
;
	.fopt		compiler,"cc65 v 2.19 - Git 4f87c7c"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "c:\Work\c64\ctest\src\helper.c", 109, 1671742138
	.export		_helpermem
	.export		_helper

.segment	"RODATA"

_helpermem:
	.byte	$21
	.byte	$22
	.byte	$23
	.byte	$24

; ---------------------------------------------------------------
; int __near__ helper (int x)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_helper: near

	.dbg	func, "helper", "00", extern, "_helper"
	.dbg	sym, "x", "00", auto, 0

.segment	"CODE"

	.dbg	line, "c:\Work\c64\ctest\src\helper.c", 4
	jsr     pushax
	.dbg	line, "c:\Work\c64\ctest\src\helper.c", 5
	ldy     #$01
	jsr     ldaxysp
	ldy     #$0D
	jsr     incaxy
	jsr     aslax1
	jmp     L0001
	.dbg	line, "c:\Work\c64\ctest\src\helper.c", 6
L0001:	jsr     incsp2
	rts

	.dbg	line
.endproc

