#include <stddef.h> // NOLINT
#include <stdint.h> // NOLINT
#include <stdbool.h> // NOLINT

#include "libc64/system.h"

void poke(const uint16_t poke_address, const uint8_t value) {
    *(address_t)(poke_address) = value;
}

uint8_t peek(const uint16_t address) {
    return *(address_t)(address);
}

void set_bit(const uint16_t address, uint8_t bit, bool enabled) {
    address_t ptr = (address_t)(address);
    uint8_t value = (enabled) ? *ptr | (1 << bit) : *ptr & ~(1 << bit);
    *ptr = value;
}

bool get_bit(const uint16_t address, uint8_t bit) {
    address_t ptr = (address_t)(address);
    return (*ptr & (1 << bit)) != 0x0;
}

void system_init() {

}

void system_disable_interrupts() {
    asm ("sei"); // NOLINT
}

void system_enable_interrupts() {
    asm ("cli"); // NOLINT
}

uint16_t _system_read_addr = 0x0;

void system_read_memory(uint16_t addr) {
    _system_read_addr = addr;
    asm ("lda %v", _system_read_addr); // NOLINT
}

void system_disable_kernal_and_basic() {

    system_disable_interrupts();

    poke(0xdc0d, 0x7f);              // disable timer interrupts which can be generated by the two CIA chips
    poke(0xdd0d, 0x7f);              // kernal uses such an interrupt to flash the cursor and scan the
                                     // keyboard, so we better stop it.

    system_read_memory(0xdc0d);      // by reading this two registers we negate any pending CIA irqs.
    system_read_memory(0xdd0d);      // if we don't do this, a pending CIA irq might occur after
                                     // we finish setting up our irq. we don't want that to happen.

    poke(0xd01a, 0x0);               // clear VIC interrupt mask bits
    poke(0xd019, 0x0);               // clear VIC interrupt request bits

    system_mem_map(0x5);             // NO kernel ROM + NO basic ROM + I/O

    system_enable_interrupts();
}

void system_enable_kernal_and_basic() {
    system_disable_interrupts();
    system_mem_map(0x7);             // kernel ROM + basic ROM + I/O
    system_enable_interrupts();
}

void system_mem_map(uint8_t bits) {
    uint8_t memFlags = peek(0x01) & 0xf8;
    memFlags |= (bits & 0x7);
    poke(0x01, memFlags);
}

// NOLINTNEXTLINE
void system_copy_charset(uint8_t* dest, size_t src_offset, size_t count) {

    uint8_t oldMemFlags;
    const uint8_t* src;

    system_disable_interrupts();

    oldMemFlags = peek(0x01);
    poke(0x1, (oldMemFlags & 0xfb));  // enable access to Character ROM
                                      // instead of mem-mapped I/O at $d000

    src = (const uint8_t*) (0xd000 +  src_offset);

    if (0 == count) count = 0x1000; // default size
    while (count) {
        *(dest++) = *(src++);
        count--;
    }

    poke(0x01, oldMemFlags);

    system_enable_interrupts();
}
