; #############################################################################
; #
; # GENERATED BY DIS64
; # test.prg
; #
; #############################################################################

*=$0801 ; load address (2049)
!byte $0c,$08,$b5,$07,$9e,$20,$32,$30,$36,$32,$00,$00,$00 ; 1973 SYS 2062

    jmp label0            ; $080E  4C 1808
    jsr $0000             ; $0811  20 0000
.buffer0 !byte $00 $00 $00 $00

label0:
    jsr label5            ; $0818  20 6A08
    lda #$2c              ; $081B  A9 2C    ; load/store A
    sta $0814             ; $081D  8D 1408
    lda #$01              ; $0820  A9 01    ; load/store A
    sta $0815             ; $0822  8D 1508
    lda $d011             ; $0825  AD 11D0  ; load/store A
    sta $0882             ; $0828  8D 8208

label1:
    lda #$ff              ; $082B  A9 FF    ; load/store A
    sta $0816             ; $082D  8D 1608

label2:
    lda #$41              ; $0830  A9 41
    ldx $0816             ; $0832  AE 1608
    sta $03ff,X           ; $0835  9D FF03
    lda $0814             ; $0838  AD 1408
    and $07               ; $083B  25 07
    sta $0817             ; $083D  8D 1708
    lda $0882             ; $0840  AD 8208
    and $f8               ; $0843  25 F8
    ora $0817             ; $0845  0D 1708
    sta $d011             ; $0848  8D 11D0
    dec $0816             ; $084B  CE 1608
    bne label2            ; $084E  D0 E0
    dec $0814             ; $0850  CE 1408
    bne label3            ; $0853  D0 0B
    dec $0814             ; $0855  CE 1408
    dec $0815             ; $0858  CE 1508
    bne label3            ; $085B  D0 03
    jmp label4            ; $085D  4C 6308

label3:
    jmp label1            ; $0860  4C 2B08

label4:
    lda $0882             ; $0863  AD 8208  ; load/store A
    sta $d011             ; $0866  8D 11D0
    rts                   ; $0869  60       ; return

label5:
    pha                   ; $086A  48       ; push to stack
    lda #$05              ; $086B  A9 05    ; load/store A
    sta $d020             ; $086D  8D 20D0
    lda #$03              ; $0870  A9 03    ; load/store A
    sta $d021             ; $0872  8D 21D0
    lda #$09              ; $0875  A9 09    ; load/store A
    sta $0286             ; $0877  8D 8602
    pla                   ; $087A  68       ; pull from stack
    rts                   ; $087B  60       ; return

    pha                   ; $087C  48       ; push to stack
    lda #$10              ; $087D  A9 10
    pla                   ; $087F  68       ; pull from stack
    rts                   ; $0880  60       ; return

    tax                   ; $0881  AA
    tax                   ; $0882  AA
    tax                   ; $0883  AA
    tax                   ; $0884  AA
    tax                   ; $0885  AA
    tax                   ; $0886  AA
    tax                   ; $0887  AA
    tax                   ; $0888  AA
    tax                   ; $0889  AA
    tax                   ; $088A  AA
    tax                   ; $088B  AA
    tax                   ; $088C  AA
    tax                   ; $088D  AA
    tax                   ; $088E  AA
    tax                   ; $088F  AA
    tax                   ; $0890  AA
    tax                   ; $0891  AA
    tax                   ; $0892  AA
    tax                   ; $0893  AA
    tax                   ; $0894  AA
    tax                   ; $0895  AA
    tax                   ; $0896  AA
    tax                   ; $0897  AA
    tax                   ; $0898  AA
    tax                   ; $0899  AA
    tax                   ; $089A  AA
    tax                   ; $089B  AA
    tax                   ; $089C  AA
    tax                   ; $089D  AA
    tax                   ; $089E  AA
    tax                   ; $089F  AA
    tax                   ; $08A0  AA
